namespace Sasm.Parsing
{
    public enum ParseTerm
    {
        Start,
        Line,
        LabelDef,
        Instruction,
        Comment,
        Operation,
        Op,
        Operand,
        RegisterAlias,
        Constant,
        Literal,
        ConstEpr,
        AddTerm,
        MulTerm,
        Absolute,
        Indirect,
        Displacement,
        Offset,
        Directive,
        Segment,
        Origin,
        Include,
        Times,
        Data,
        DataConstant,
        Warning,
        Const
    }
}