namespace Sasm.Parsing
{
    public enum ParseTreeNodeType
    {
        Start,
        Line,
        Instruction,
        Operation,
        Op,
        Operand,
        RegisterAlias,
        Constant,
        Literal,
        ConstExpression,
        AddTerm,
        MulTerm,
        AbsoluteMemAccess,
        IndirectMemAccess,
        DisplacementMemAccess,
        OffsetMemAccess,
        Directive,
        SegmentDirective,
        OriginDirective,
        IncludeDirective,
        TimesDirective,
        DataDirective,
        DataConstant,
        Warning,
        ConstDirective,
        Terminal,
    }
}